const PDFDocument = require('pdfkit');
const Scan = require('../models/Scan');

/**
 * Generate PDF report for a scan
 */
exports.generatePDFReport = async (req, res) => {
  try {
    const scan = await Scan.findOne({
      _id: req.params.id,
      user: req.user.id
    }).populate('user', 'name email');

    if (!scan) {
      return res.status(404).json({ error: 'Scan not found' });
    }

    // Create PDF document
    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=scan-report-${scan._id}.pdf`);

    // Pipe PDF to response
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor('#3b82f6').text('LinkGuard Security Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#666').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);

    // URL Information
    doc.fontSize(16).fillColor('#000').text('URL Analysis', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333').text(`URL: ${scan.url}`);
    doc.text(`Scanned: ${scan.createdAt.toLocaleString()}`);
    doc.text(`Scan Type: ${scan.scanType || 'standard'}`);
    doc.moveDown();

    // Risk Score
    doc.fontSize(16).fillColor('#000').text('Risk Assessment', { underline: true });
    doc.moveDown(0.5);
    
    const statusColor = scan.status === 'safe' ? '#10b981' : scan.status === 'suspicious' ? '#f59e0b' : '#ef4444';
    doc.fontSize(14).fillColor(statusColor).text(`Status: ${scan.status.toUpperCase()}`);
    doc.fontSize(11).fillColor('#333').text(`Risk Score: ${scan.riskScore}/100`);
    doc.moveDown();

    // Heuristic Analysis
    if (scan.results?.heuristicAnalysis) {
      doc.fontSize(16).fillColor('#000').text('Heuristic Analysis', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333');
      
      const heuristics = scan.results.heuristicAnalysis;
      doc.text(`• URL Length: ${heuristics.urlLength || 'N/A'}`);
      doc.text(`• Has HTTPS: ${heuristics.hasHttps ? 'Yes' : 'No'}`);
      doc.text(`• Is Shortened: ${heuristics.isShortened ? 'Yes' : 'No'}`);
      doc.text(`• Suspicious Keywords: ${heuristics.hasSuspiciousKeywords ? 'Detected' : 'None'}`);
      doc.text(`• IP-based URL: ${heuristics.isIpBased ? 'Yes' : 'No'}`);
      doc.moveDown();
    }

    // Google Safe Browsing
    if (scan.results?.googleSafeBrowsing) {
      doc.fontSize(16).fillColor('#000').text('Google Safe Browsing', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333');
      
      const google = scan.results.googleSafeBrowsing;
      doc.text(`Status: ${google.isSafe ? 'Safe' : 'Threat Detected'}`);
      if (google.threats && google.threats.length > 0) {
        doc.text(`Threats: ${google.threats.join(', ')}`);
      }
      doc.moveDown();
    }

    // VirusTotal
    if (scan.results?.virusTotal) {
      doc.fontSize(16).fillColor('#000').text('VirusTotal Analysis', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333');
      
      const vt = scan.results.virusTotal;
      doc.text(`Detections: ${vt.positives || 0}/${vt.total || 0} engines`);
      if (vt.positives > 0) {
        doc.fillColor('#ef4444').text(`⚠️ ${vt.positives} security vendors flagged this URL as malicious`);
      }
      doc.moveDown();
    }

    // Warnings
    if (scan.results?.heuristicAnalysis?.warnings?.length > 0) {
      doc.fontSize(16).fillColor('#000').text('Security Warnings', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#ef4444');
      
      scan.results.heuristicAnalysis.warnings.forEach(warning => {
        doc.text(`⚠️ ${warning}`);
      });
      doc.moveDown();
    }

    // Footer
    doc.fontSize(8).fillColor('#999').text(
      'This report is generated by LinkGuard AI-Powered Link Safety Checker. ' +
      'Results should be used as guidance only. Always exercise caution when visiting unknown URLs.',
      50,
      doc.page.height - 50,
      { align: 'center', width: doc.page.width - 100 }
    );

    // Finalize PDF
    doc.end();
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate PDF report' });
  }
};

/**
 * Generate CSV export of scan history
 */
exports.generateCSVReport = async (req, res) => {
  try {
    const scans = await Scan.find({ user: req.user.id })
      .sort({ createdAt: -1 })
      .limit(1000);

    // CSV headers
    let csv = 'Date,URL,Status,Risk Score,Scan Type,Google Safe Browsing,VirusTotal Detections\n';

    // CSV rows
    scans.forEach(scan => {
      const date = scan.createdAt.toISOString();
      const url = `"${scan.url.replace(/"/g, '""')}"`;
      const status = scan.status;
      const riskScore = scan.riskScore;
      const scanType = scan.scanType || 'standard';
      const googleSafe = scan.results?.googleSafeBrowsing?.isSafe ? 'Safe' : 'Threat';
      const vtDetections = scan.results?.virusTotal?.positives || 0;

      csv += `${date},${url},${status},${riskScore},${scanType},${googleSafe},${vtDetections}\n`;
    });

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename=linkguard-scan-history.csv');
    res.send(csv);
  } catch (error) {
    console.error('CSV generation error:', error);
    res.status(500).json({ error: 'Failed to generate CSV report' });
  }
};
